name: echarts_flutter_plus
description: "Flutter plugin for rendering Apache ECharts charts on web."
version: 0.0.8
homepage: https://github.com/noeljolly09/echarts_flutter_plus
repository: https://github.com/noeljolly09/echarts_flutter_plus
issue_tracker: https://github.com/noeljolly09/echarts_flutter_plus/issues
documentation: https://github.com/noeljolly09/echarts_flutter_plus/blob/main/README.md
license: MIT

topics:
  - echarts
  - chart
  - apache
  - visualization

environment:
  sdk: ^3.7.0
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  web: ^1.1.1
  plugin_platform_interface: ^2.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  plugin:
    platforms:
      web:
        pluginClass: EchartsFlutterPlusWeb
        fileName: echarts_flutter_plus_web.dart
